feat: akamai DNS support
apiaryio/spf-tools pull request #4
Opened 2017-04-27 13:27 UTC by nadade

2017-04-27 13:31 UTC, nadade commented
![](https://github.trello.services/images/mini-trello-icon.png) [figure out a way to refresh them periodically](https://trello.com/c/DXhRlMEP/527-figure-out-a-way-to-refresh-them-periodically)

2017-05-04 10:51 UTC, miiila requested changes
Great, I am looking forward to have this in production.

I did just a first part of a review, since some parts are missing:

- readme or any other basic documentation
- CI setup in order to have the tests run automatically
- IIRC all the new libraries should use ES2015/16

2017-05-04 10:51 UTC, miiila commented on plugins/akamai.js
> +    cb(error,  JSON.parse(body));
I'd say it's not safe for the asynchronous calls. If the `process.exit(1)` would be delayed, it could trigger callback execution.

2017-05-04 10:51 UTC, miiila commented on package.json
> +    "test": "echo \"Error: no test specified\" && exit 1"
I'd say this is not a true ;-)

2017-05-04 10:51 UTC, miiila commented on tests/akamai/test-akamai.js
> +      assert.deepEqual(actual_zonefile, expected_zonefile);
I am missing the reset of the added domains. I agree with integration test, but it should cleanup IHMO.

2017-05-04 10:51 UTC, miiila commented on plugins/akamai.js
> +    path: '.edgerc',
What's the purpose of this file? I can see it's ignored in git, so is it created automatically?

2017-06-07 10:55 UTC, nadade commented
@miiila added CI build and README instructions, updated the code to do reasonable logging and added comments.

2017-06-19 13:44 UTC, miiila approved these changes
Thank you for the changes and docs! ☕️

2017-06-19 13:44 UTC, merged